# Generated by Django 3.2.4 on 2022-01-30 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_vehicles_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
